version: '3'
services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27020:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: challenge

volumes:
  mongodb_data:
